-- ???? seed
insert into public.census_brands (id, english_name, chinese_name, aliases, status, created_at, updated_at)
values
  ('brand-1', 'AKG', '', array[]::text[], 'approved', now(), now()),
  ('brand-2', 'Astell&Kern', '', array['AK', 'A&K'], 'approved', now(), now()),
  ('brand-3', 'Audio-Technica', '鐵三角', array['ATH'], 'approved', now(), now()),
  ('brand-4', 'Beyerdynamic', '拜耳', array['拜亞'], 'approved', now(), now()),
  ('brand-5', 'Campfire Audio', '', array['Campfire'], 'approved', now(), now()),
  ('brand-6', 'Cayin', '凱音', array[]::text[], 'approved', now(), now()),
  ('brand-7', 'Chord Electronics', '', array['Chord'], 'approved', now(), now()),
  ('brand-8', 'Denafrips', '', array[]::text[], 'approved', now(), now()),
  ('brand-9', 'FiiO', '飛傲', array['FIIO', 'Fiio'], 'approved', now(), now()),
  ('brand-10', 'final', '', array['Final', 'Final Audio'], 'approved', now(), now()),
  ('brand-11', 'FOCAL', '', array['Focal'], 'approved', now(), now()),
  ('brand-12', 'FOSTEX', '', array['Fostex'], 'approved', now(), now()),
  ('brand-13', 'Grado Labs', '', array['Grado'], 'approved', now(), now()),
  ('brand-14', 'Hiby', '', array['HiBy'], 'approved', now(), now()),
  ('brand-15', 'HIFIMAN', '海菲曼', array['HiFiMAN'], 'approved', now(), now()),
  ('brand-16', 'iBasso Audio', '', array['iBasso'], 'approved', now(), now()),
  ('brand-17', 'iFi audio', '', array['ifi', 'iFi'], 'approved', now(), now()),
  ('brand-18', 'JVC', '杰偉世', array['Victor', 'JVC Victor'], 'approved', now(), now()),
  ('brand-19', 'LUXMAN', '', array['Luxman'], 'approved', now(), now()),
  ('brand-20', 'Luxury&Precision', '樂彼', array['L&P'], 'approved', now(), now()),
  ('brand-21', 'Meze Audio', '', array['Meze'], 'approved', now(), now()),
  ('brand-22', 'MOONDROP', '水月雨', array['Moondrop'], 'approved', now(), now()),
  ('brand-23', 'RME', '', array[]::text[], 'approved', now(), now()),
  ('brand-24', 'Schiit Audio', '', array['Schiit'], 'approved', now(), now()),
  ('brand-25', 'See Audio', '', array[]::text[], 'approved', now(), now()),
  ('brand-26', 'Sennheiser', '聲海', array['森海', '聲海'], 'approved', now(), now()),
  ('brand-27', 'Shanling', '山靈', array[]::text[], 'approved', now(), now()),
  ('brand-28', 'Shure', '舒爾', array[]::text[], 'approved', now(), now()),
  ('brand-29', 'SMSL', '雙木三林', array['S.M.S.L'], 'approved', now(), now()),
  ('brand-30', 'SONY', '索尼', array['Sony'], 'approved', now(), now()),
  ('brand-31', 'STAX', '', array['Stax'], 'approved', now(), now()),
  ('brand-32', 'Tangzu', '唐族', array['TANGZU'], 'approved', now(), now()),
  ('brand-33', 'TEAC', '', array['Teac'], 'approved', now(), now()),
  ('brand-34', 'TOPPING', '拓品', array['Topping'], 'approved', now(), now()),
  ('brand-35', 'Xenns', '', array[]::text[], 'approved', now(), now()),
  ('brand-36', 'Yamaha', '山葉', array[]::text[], 'approved', now(), now())
on conflict (id) do update set
  english_name = excluded.english_name,
  chinese_name = excluded.chinese_name,
  aliases = excluded.aliases,
  status = excluded.status,
  updated_at = now();
